apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  selector: {}
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --storage.postgres.dsn=$(POSTGRES_DSN)
          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DSN
                  name: api-server-secrets
          image: ghcr.io/yunusemre12500/url-shortaner/api-server
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          name: api-server
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostUsers: false
      imagePullSecrets:
        - name: ghcr-credentials
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: secrets
          secret:
            secretName: url-shortaner-api-server-secrets
            defaultMode: 0440
            optional: false
